kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: changelog-volume
  namespace: liquibase
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard